sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  allow_failures:
  - python: "3.7"
install:
  - pip install git+https://github.com/PyUtilib/pyutilib
  - pip install git+https://github.com/Pyomo/pyomo
  - pip install -r requirements.txt
  - pip install tox-travis codecov
script:
  - python setup.py test
after_success:
  - codecov
