name: Build and publish docs

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs/
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_build/html/